"use client";
import { useQuery } from "@tanstack/react-query";
import { Shell, PageHeader } from "@/components/chrome";
import { api } from "@/lib/api";

export default function SourcesPage() {
  const query = useQuery({ queryKey: ["data-sources"], queryFn: api.sources });
  return <Shell><PageHeader eyebrow="Data sources / observability" title="Know where the data comes from."><span className="text-xs text-slate-500">Keys stay server-side</span></PageHeader>{query.isPending ? <SourceSkeleton /> : query.isError ? <p className="rounded-xl border border-amber/40 p-5 text-sm text-amber">Source status is temporarily unavailable.</p> : <div className="grid gap-4 md:grid-cols-2">{(query.data || []).map(source => <SourceCard key={String(source.provider)} source={source} />)}</div>}<p className="mt-8 max-w-3xl text-xs leading-6 text-slate-500">Open-source software licenses and the data rights of upstream sports services are separate questions. Secondary and experimental sources must be reviewed for coverage and commercial-use terms before production reliance.</p></Shell>;
}

function SourceCard({ source }: { source: Record<string, unknown> }) { const enabled = Boolean(source.enabled); const configured = Boolean(source.configured); const state = !enabled ? "Disabled" : !configured ? "Not configured" : source.healthy === false ? "Unavailable" : "Enabled"; return <article className="rounded-2xl border border-line bg-panel/80 p-6"><div className="flex items-start justify-between gap-5"><div><h2 className="font-semibold text-white">{String(source.name || source.provider)}</h2><p className="mt-2 text-xs uppercase tracking-[.14em] text-mint">{String(source.role || "provider")}</p><p className="mt-3 max-w-md text-sm leading-6 text-slate-400">{String(source.detail || "Provider health and coverage metadata")}</p></div><span className={`rounded-full px-3 py-1 text-[10px] uppercase tracking-wider ${state === "Enabled" ? "bg-mint/10 text-mint" : "bg-white/5 text-slate-500"}`}>{state}</span></div><div className="mt-6 border-t border-line pt-4 text-xs text-slate-500"><p>Capabilities: <span className="text-slate-300">{Array.isArray(source.capabilities) ? source.capabilities.join(", ") : "Declared by provider"}</span></p><p className="mt-2">{source.experimental ? "Experimental; isolated from the production default path." : "Primary or configured market/data path."}</p></div></article>; }
function SourceSkeleton() { return <div className="grid gap-4 md:grid-cols-2">{[1, 2, 3, 4].map(item => <div key={item} className="h-44 animate-pulse rounded-2xl border border-line bg-panel/70" />)}</div>; }
