"use client";
import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Shell, PageHeader } from "@/components/chrome";
import { api, MarketValue } from "@/lib/api";

export default function ValueFinderPage() {
  const [profile, setProfile] = useState("balanced");
  const [sport, setSport] = useState("all");
  const [family, setFamily] = useState("all");
  const query = useQuery({ queryKey: ["opportunities", profile], queryFn: () => api.opportunities(profile) });
  const values = useMemo(() => (query.data || []).filter(item => sport === "all" || item.sport === sport).filter(item => family === "all" || item.market_family === family), [family, query.data, sport]);
  const families = Array.from(new Set((query.data || []).map(item => item.market_family))).sort();
  return <Shell><PageHeader eyebrow="Market intelligence / pre-match" title="Find modelled price gaps."><span className="text-xs text-slate-500">No accumulator construction in Stage Three</span></PageHeader><section className="mb-6 grid gap-4 border-y border-line py-5 md:grid-cols-[1fr_1fr_1fr_auto]"><label className="grid gap-2 text-xs text-slate-500">Risk profile<select value={profile} onChange={event => setProfile(event.target.value)} className="rounded-lg border border-line bg-panel px-3 py-2 text-sm text-white"><option value="conservative">Conservative</option><option value="balanced">Balanced</option><option value="aggressive">Aggressive</option></select></label><label className="grid gap-2 text-xs text-slate-500">Sport<select value={sport} onChange={event => setSport(event.target.value)} className="rounded-lg border border-line bg-panel px-3 py-2 text-sm text-white"><option value="all">All sports</option><option value="football">Football</option><option value="basketball">Basketball</option></select></label><label className="grid gap-2 text-xs text-slate-500">Market family<select value={family} onChange={event => setFamily(event.target.value)} className="rounded-lg border border-line bg-panel px-3 py-2 text-sm text-white"><option value="all">All families</option>{families.map(item => <option key={item} value={item}>{item}</option>)}</select></label><div className="self-end text-xs text-slate-500">{values.length} fresh candidate{values.length === 1 ? "" : "s"}</div></section>{query.isPending ? <ValueSkeleton /> : query.isError ? <p className="rounded-xl border border-amber/40 p-5 text-sm text-amber">Opportunities are temporarily unavailable.</p> : !values.length ? <div className="border-t border-line pt-8"><p className="text-sm text-slate-300">No qualifying market.</p><p className="mt-2 max-w-xl text-sm leading-6 text-slate-500">A market needs fresh odds, compatible settlement, model support, sufficient data, and a positive risk-profile filter. Empty results are valid.</p></div> : <ValueTable values={values} />}</Shell>;
}

function ValueTable({ values }: { values: MarketValue[] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[1060px] text-left text-xs"><thead className="border-b border-line text-slate-500"><tr>{["Fixture", "Market", "Bookmaker", "Odds", "Model P", "Fair odds", "No-vig edge", "EV", "Confidence", "Reliability", "Freshness"].map(label => <th key={label} className="px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-line">{values.map((value, index) => <tr key={`${value.fixture_id}-${value.market_family}-${value.selection}-${index}`} className="transition hover:bg-white/[.03]"><td className="px-3 py-4 font-mono text-slate-400">{value.fixture_id.slice(0, 10)}</td><td className="px-3 py-4 text-slate-300">{value.market_family} / {value.selection}{value.line == null ? "" : ` ${value.line}`}</td><td className="px-3 py-4 text-slate-400">{value.bookmaker}</td><td className="px-3 py-4 font-mono text-white">{value.bookmaker_odds?.toFixed(2) || "-"}</td><td className="px-3 py-4 font-mono text-mint">{(value.model_probability * 100).toFixed(1)}%</td><td className="px-3 py-4 font-mono text-slate-300">{value.fair_odds?.toFixed(2) || "-"}</td><td className={`px-3 py-4 font-mono ${(value.novig_probability_edge || 0) > 0 ? "text-mint" : "text-slate-400"}`}>{value.novig_probability_edge == null ? "-" : `${(value.novig_probability_edge * 100).toFixed(1)}%`}</td><td className="px-3 py-4 font-mono text-slate-300">{value.expected_value == null ? "-" : `${(value.expected_value * 100).toFixed(1)}%`}</td><td className="px-3 py-4 font-mono text-slate-300">{value.confidence.toFixed(0)}/100</td><td className="px-3 py-4 font-mono text-slate-300">{value.market_reliability == null ? "-" : `${value.market_reliability.toFixed(0)}/100`}</td><td className="px-3 py-4 text-slate-400">{value.freshness.status}</td></tr>)}</tbody></table></div>; }
function ValueSkeleton() { return <div className="space-y-3">{[1, 2, 3, 4, 5].map(item => <div key={item} className="h-14 animate-pulse border-b border-line bg-panel/40" />)}</div>; }
