import React from "react";
import Link from "next/link";
import type { LiveFixture } from "@/lib/api";

export function LiveCard({ fixture }: { fixture: LiveFixture }) {
  const homeKey = fixture.sport === "football" ? "home_win" : "home_moneyline";
  const home = fixture.live_probability?.[homeKey]; const pre = fixture.pre_match_probability?.[homeKey];
  const age = fixture.data_quality?.state_age_seconds;
  return <Link href={`/live/${fixture.id}`} className="block rounded-2xl focus:outline-none focus:ring-2 focus:ring-mint/70"><article className="rounded-2xl border border-line bg-panel/80 p-5 transition hover:border-mint/50"><div className="flex items-center justify-between text-xs text-slate-500"><span>{fixture.competition || "Competition unavailable"}</span><span className="rounded-full bg-red-400/15 px-2 py-1 font-bold uppercase tracking-wider text-red-300">{fixture.status === "halftime" ? "Halftime" : "Live"}</span></div><div className="mt-5 grid grid-cols-[1fr_auto] items-center gap-4"><div className="space-y-3 text-sm font-medium"><p>{fixture.home}</p><p>{fixture.away}</p></div><div className="text-right text-xl font-semibold tabular-nums"><p>{fixture.home_score ?? "—"}</p><p>{fixture.away_score ?? "—"}</p></div></div><div className="mt-5 flex items-center justify-between border-t border-line pt-3 text-xs text-slate-500"><span>{fixture.clock || fixture.period || "In progress"}</span><span>{age == null ? "Age unknown" : `${age}s old`}</span></div><div className="mt-4 rounded-xl border border-line bg-ink/50 p-3"><div className="flex items-center justify-between text-xs uppercase tracking-[.14em] text-slate-500"><span>Home probability</span><span className="text-mint">{fixture.data_quality?.status || "UNKNOWN"}</span></div><p className="mt-2 text-lg text-white">{home == null ? "—" : `${Math.round(home * 100)}%`} <span className="text-xs text-slate-500">pre {pre == null ? "—" : `${Math.round(pre * 100)}%`} · {fixture.probability_delta?.[homeKey] == null ? "—" : `${fixture.probability_delta[homeKey] >= 0 ? "+" : ""}${Math.round(fixture.probability_delta[homeKey] * 100)} pp`}</span></p><p className="mt-1 text-xs text-slate-500">Confidence {fixture.confidence == null ? "—" : `${Math.round(fixture.confidence)} / 100`} · {fixture.calibration_status || "INSUFFICIENT_EVIDENCE"}</p></div>{fixture.warnings?.length ? <p className="mt-3 text-xs text-amber">{fixture.warnings[0]}</p> : <p className="mt-3 text-xs text-slate-500">Open for prediction and market detail</p>}</article></Link>;
}
